name: codi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - sqlparse=0.4.1
  - libpq=12.9
  - djangorestframework=3.13.1
  - llvm-openmp
  - xz=5.2.5
  - zlib=1.2.11
  - nltk
  - django=3.2.5
  - ncurses=6.3
  - bzip2=1.0.8
  - threadpoolctl=2.2.0
  - openssl
  - tqdm=4.63.0
  - intel-openmp=2021.4.0
  - uritemplate=4.1.1
  - python-dotenv=0.20.0
  - tk=8.6.11
  - libedit=3.1.20210910
  - mkl_fft=1.3.1
  - libcxx=12.0.0
  - pip
  - sqlite=3.38.2
  - pytz=2021.3
  - typing_extensions=4.1.1
  - blas=1.0
  - libgfortran
  - requests
  - mkl=2021.4.0
  - krb5=1.19.2
  - ca-certificates
  - asgiref=3.4.1
  - mkl_random=1.2.2
  - readline=8.1.2
  - emoji=1.6.3
  - libffi=3.3
  - joblib=1.1.0
  - tzdata=2022a
  - wheel=0.37.1
  - numpy-base=1.21.5
  - python-dateutil=2.8.2
  - six=1.16.0
  - colorama=0.4.4
  - imbalanced-learn
